# Generated by Django 5.0.4 on 2024-08-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0002_book_author_book_is_bestselling_alter_book_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="is_bestselling",
            field=models.BooleanField(default=False),
        ),
    ]
